// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3n3o_EXQ5Q047J6Y00cr2rnisNgPp3zE',
    appId: '1:436573396589:web:1ac9aa275ca761c6916964',
    messagingSenderId: '436573396589',
    projectId: 'fir-demo-project-57fd1',
    authDomain: 'fir-demo-project-57fd1.firebaseapp.com',
    databaseURL: 'https://fir-demo-project-57fd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-project-57fd1.appspot.com',
    measurementId: 'G-M274C8T7P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rzvIClgP9SAFQXZjWm-wvgJ9IhxxeqY',
    appId: '1:436573396589:android:7c2a8c7497e20b44916964',
    messagingSenderId: '436573396589',
    projectId: 'fir-demo-project-57fd1',
    databaseURL: 'https://fir-demo-project-57fd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-project-57fd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3sNCWiuFmDW89yo54GM9wvN_dWn02boA',
    appId: '1:436573396589:ios:24d17cf559f56aad916964',
    messagingSenderId: '436573396589',
    projectId: 'fir-demo-project-57fd1',
    databaseURL: 'https://fir-demo-project-57fd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-project-57fd1.appspot.com',
    androidClientId: '436573396589-meso1fsgm19fs9l6ls53gsf6kh4v7fco.apps.googleusercontent.com',
    iosClientId: '436573396589-avetupdc5dm1ccnhekp31adbpb3cank9.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappking1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3sNCWiuFmDW89yo54GM9wvN_dWn02boA',
    appId: '1:436573396589:ios:24d17cf559f56aad916964',
    messagingSenderId: '436573396589',
    projectId: 'fir-demo-project-57fd1',
    databaseURL: 'https://fir-demo-project-57fd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-project-57fd1.appspot.com',
    androidClientId: '436573396589-meso1fsgm19fs9l6ls53gsf6kh4v7fco.apps.googleusercontent.com',
    iosClientId: '436573396589-avetupdc5dm1ccnhekp31adbpb3cank9.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappking1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3n3o_EXQ5Q047J6Y00cr2rnisNgPp3zE',
    appId: '1:436573396589:web:9048693ccdb5a0ea916964',
    messagingSenderId: '436573396589',
    projectId: 'fir-demo-project-57fd1',
    authDomain: 'fir-demo-project-57fd1.firebaseapp.com',
    databaseURL: 'https://fir-demo-project-57fd1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-project-57fd1.appspot.com',
    measurementId: 'G-ZVEM7YVSRH',
  );
}
